services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password}
      POSTGRES_DB: staddb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_secure_password}
      - POSTGRES_DB=staddb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: unless-stopped
  frontend:
      build: ./frontend  # Assuming your streamlit code is in a 'frontend' folder
      ports:
        - "8501:8501"
      environment:
        # Tell Streamlit to hit the internal Docker API service, not localhost
        - API_URL=http://api:8000/api/v1/anomalies
      depends_on:
        - api
      restart: unless-stopped

volumes:
  postgres_data:
