import pandas as pd
import geopandas as gpd
from shapely.wkt import loads
from sqlalchemy import create_engine
import sqlalchemy
import os
from dotenv import load_dotenv
import urllib.parse

load_dotenv()

def import_to_postgis(file_path, db_connection_string, table_name="earthquakes"):
    print("--- Step 1: Loading Processed Data ---")
    # If loading from the CSV generated by the previous step:
    df = pd.read_csv(file_path)

    # Reconstruct the GeoDataFrame from the WKT 'geom' string
    print("Reconstructing geometry from Well-Known Text (WKT)...")
    df['geometry'] = df['geom'].apply(loads)

    # Drop the temporary text string column to avoid duplicating data
    df = df.drop(columns=['geom'])

    # Convert to a proper GeoDataFrame using Japan's standard coordinate system (WGS84)
    gdf = gpd.GeoDataFrame(df, geometry='geometry', crs="EPSG:4326")

    print("--- Step 2: Connecting to PostgreSQL ---")
    # Connection string format: 'postgresql://username:password@host:port/database_name'
    engine = create_engine(db_connection_string)

    print(f"--- Step 3: Writing to Database Table: '{table_name}' ---")
    # to_postgis automatically maps the geometry column and infers the type
    gdf.to_postgis(
            name=table_name,
            con=engine,
            if_exists='replace',  
            index=False,
            dtype={'metadata': sqlalchemy.types.JSON} 
            )
    print(f"Successfully imported {len(gdf)} rows into PostGIS!")

my_password = os.getenv('POSTGRES_PASSWORD')
encoded_password = urllib.parse.quote_plus(my_password)
CONN_STR = f'postgresql://postgres:{encoded_password}@localhost:5432/staddb'
import_to_postgis('Outputs/cleaned_earthquakes.csv', CONN_STR)
